"""add analytics_events table

Revision ID: 3a57cba15610
Revises: 447ec9d9f144
Create Date: 2026-05-15 12:38:24.312212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a57cba15610'
down_revision: Union[str, None] = 'c8a1f7d3b2e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('pharmacy_branch_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analytics_branch_created', 'analytics_events', ['pharmacy_branch_id', 'created_at'], unique=False)
    op.create_index('ix_analytics_clinic_created', 'analytics_events', ['clinic_id', 'created_at'], unique=False)
    op.create_index('ix_analytics_event_created', 'analytics_events', ['event_type', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analytics_event_created', table_name='analytics_events')
    op.drop_index('ix_analytics_clinic_created', table_name='analytics_events')
    op.drop_index('ix_analytics_branch_created', table_name='analytics_events')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
