"""add map_link to pharmacy_branches

Revision ID: 4304bd405bb3
Revises: b3f70121c0ec
Create Date: 2026-04-28 22:27:13.596527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4304bd405bb3'
down_revision: Union[str, None] = 'b3f70121c0ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pharmacy_branches', sa.Column('map_link', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pharmacy_branches', 'map_link')
    # ### end Alembic commands ###
