"""add whatsapp instagram to pharmacy_companies

Revision ID: 457e5f809dc2
Revises: 4304bd405bb3
Create Date: 2026-04-29 11:07:24.673031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '457e5f809dc2'
down_revision: Union[str, None] = '4304bd405bb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pharmacy_companies', sa.Column('whatsapp', sa.String(length=30), nullable=True))
    op.add_column('pharmacy_companies', sa.Column('instagram', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pharmacy_companies', 'instagram')
    op.drop_column('pharmacy_companies', 'whatsapp')
    # ### end Alembic commands ###
