"""add doctor_profile_updates table

Revision ID: 5a381110be93
Revises: a2899636a892
Create Date: 2026-04-30 12:31:22.144748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a381110be93'
down_revision: Union[str, None] = 'a2899636a892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_profile_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('full_name_ru', sa.String(length=255), nullable=True),
    sa.Column('specialization_ru', sa.String(length=255), nullable=True),
    sa.Column('bio_ru', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('consultation_language', sa.String(length=100), nullable=True),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('cover_photo_url', sa.String(length=512), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('has_online', sa.Boolean(), nullable=True),
    sa.Column('has_offline', sa.Boolean(), nullable=True),
    sa.Column('online_price', sa.Float(), nullable=True),
    sa.Column('offline_price', sa.Float(), nullable=True),
    sa.Column('online_duration_min', sa.Integer(), nullable=True),
    sa.Column('offline_duration_min', sa.Integer(), nullable=True),
    sa.Column('contacts_json', sa.Text(), nullable=True),
    sa.Column('services_json', sa.Text(), nullable=True),
    sa.Column('schedules_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor_profile_updates')
    # ### end Alembic commands ###
