"""add rejection_reason to doctors

Revision ID: 7542923ce5c1
Revises: 7a14fad7adea
Create Date: 2026-04-28 10:16:03.220252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7542923ce5c1'
down_revision: Union[str, None] = '7a14fad7adea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'rejection_reason')
    # ### end Alembic commands ###
