"""add cover_photo_url to doctors

Revision ID: a2899636a892
Revises: 457e5f809dc2
Create Date: 2026-04-29 19:00:46.385449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2899636a892'
down_revision: Union[str, None] = '457e5f809dc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('cover_photo_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'cover_photo_url')
    # ### end Alembic commands ###
