"""add_map_url_to_clinics

Revision ID: b3f70121c0ec
Revises: 7542923ce5c1
Create Date: 2026-04-28 16:12:05.056084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3f70121c0ec'
down_revision: Union[str, None] = '7542923ce5c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinics', sa.Column('map_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinics', 'map_url')
    # ### end Alembic commands ###
