"""add cover_photo_url to pharmacy_companies

Revision ID: dbd567060228
Revises: 0519ddb41b41
Create Date: 2026-05-11 18:57:39.548338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbd567060228'
down_revision: Union[str, None] = '0519ddb41b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pharmacy_companies', sa.Column('cover_photo_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pharmacy_companies', 'cover_photo_url')
    # ### end Alembic commands ###
