"""fix fk constraints and doctor clinic relation

Revision ID: edac691582da
Revises: 0009
Create Date: 2026-04-28 09:01:30.898295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edac691582da'
down_revision: Union[str, None] = '0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'clinics', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'pharmacy_companies', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uq_users_refresh_token', 'users', type_='unique')
    op.drop_index('ix_users_refresh_token', table_name='users')
    op.create_index(op.f('ix_users_refresh_token'), 'users', ['refresh_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_refresh_token'), table_name='users')
    op.create_index('ix_users_refresh_token', 'users', ['refresh_token'], unique=False)
    op.create_unique_constraint('uq_users_refresh_token', 'users', ['refresh_token'])
    op.drop_constraint(None, 'pharmacy_companies', type_='foreignkey')
    op.drop_constraint(None, 'clinics', type_='foreignkey')
    # ### end Alembic commands ###
